### PR TITLE
Removed functions in application.java that may no longer be needed

### PR DESCRIPTION
**Pull request by leenlab2**
Some of the functions in Application.java are not actually that useful for our purposes, and this PR suggests removing them.

## Context

The first function, commandLineRunner, was copied in during the springboot setup tutorial, but seems to only be printing information to the console. The second function, corsConfigurer, was added as an attempt to fix a cross-origin request policy error, but that error is being handled by the @CrossOrigin annotation in another file, so this may not be necessary.

## Your Changes

**Description**:

Removed the two functions mentioned..

**Type of change** (select all that apply):

- [x] Refactoring (changing code structure only)
- [x] Breaking change (changing code functionality)

## Testing

Spring still seems to run under the bootRun command, but I am unsure if it is still sending and receiving information when this is applied to the server (rather than locally).

## Notes

Can someone test this works when calling from hosted front-end, and when answering from hosted back-end?

## Checklist

- [x] Code is up to date with main branch (no merge conflicts)
- [x] Code has been properly tested
- [x] Code has been properly documented
- [x] One or two people have reviewed this pull request

### CODE REVIEW

**Review by dhruvaa02 — APPROVED** [review]
I saw this as well and was going to suggest removing it too. Even if it did anything, it wouldn't be working currently so I'm sure this is redundant.

**Comment by leenlab2** [comment]
> I saw this as well and was going to suggest removing it too. Even if it did anything, it wouldn't be working currently so I'm sure this is redundant.

Can you try testing it on the server? If something breaks because of the Senso API changes, it will be obvious. But I want to see if we can still call the server at all.

**Comment by dhruvaa02** [comment]
> > I saw this as well and was going to suggest removing it too. Even if it did anything, it wouldn't be working currently so I'm sure this is redundant.
> 
> @dhruvaa02 Can you try testing it on the server? If something breaks because of the Senso API changes, it will be obvious. But I want to see if we can still call the server at all.

I tested this branch on the EC2 and everything works...I'm still able to connect to the domain and see greetings from spring boot as necessary.

**Review by Infinityworld13 — APPROVED** [review]
Looks to be working in order

**Pull request merged**
