### PR TITLE
Refactoring File Structure

### PR DESCRIPTION
**Pull request by Alamgir-K**
Refactoring file structure

## Context

 Having the sql files in a separate folder was unnecessary so moving the java files into our existing src folder and moving the sqlconnection lib to our existing lib folder makes more sense

## Your Changes

**Description**:
 I have moved the contents of the database folder into their respective places. the data folder is in our root directory, the sqlconnection file has been moved under a new dataprocess package under src and the sql java lib has been moved to the main lib folder
New Structure:
```
├── data
    └── csv files
└── lib
     └── lib files
└── src/main
    └── java/com/aviva
        └── packages
    └── resources
   ```

**Type of change** (select all that apply):

- [x] Refactoring (changing code structure only)

## Testing

 I am leaving the testing to whoever merges from the front-end

## Notes

 Someone from the front-end needs to run the gradle to see if everything works properly before merging

## Checklist

- [x] Code is up to date with main branch (no merge conflicts)
- [ ] One or two people have reviewed this pull request

### CODE REVIEW

**Comment by dhruvaa02** [comment]
Just realised this won't work until you refactor all of the hard-coded file paths. Have to change that before we merge this.

**Comment by leenlab2** [comment]
This PR is related to Issue #9 ! Remember to reference the issues :)

**Review by leenlab2 — CHANGES_REQUESTED** [review]
Good start, some minor errors:
- SQLConnection should be under "DataAccess", as an implementation of one of the interfaces (for now, though, just move it to DataAccess).
- You forgot to add a package name to the top of the SQLCon file `package com.aviva.DataAccess`
- Intellij wants you to `import java.sql.Statement` also, it was giving me an error

After these changes though, gradlew was still running as expected on my end!

**Review by leenlab2 — APPROVED** [review]
All good

**Pull request merged**
