### PR TITLE
Updated Car Dataset

### PR DESCRIPTION
**Pull request by Infinityworld13**
Updated Car Dataset with full sample information

## Context

The current dataset with had was short (10 cars) and with made up information. 

## Your Changes

**Description**:

Expanded the dataset to include 1000+ cars of multiple brands and models. It now also included new columns for VIN (vehicle identification number) and image with a html link to a car brand image.

**Type of change** (select all that apply):

- [x] Other (please specify): New data

## Testing

All previous dataset tests should apply to this dataset

## Checklist

- [x] Code is up to date with main branch (no merge conflicts)
- [x] Code has been properly tested
- [x] Code has been properly documented
- [x] One or two people have reviewed this pull request

### CODE REVIEW

**Review by dhruvaa02 — APPROVED** [review]
This shouldn't change any functionality so this looks good to me.

**Review by leenlab2 — COMMENTED** [review]
I noticed some cars have weird prices. I assume this is because this is a set of used cars, so let us filter by the following:
- Exclude if price = 0
- Include only if year is 2019, 2020

**Comment by dhruvaa02** [comment]
Why do you only want to include if the year is 2019, 2020? I agree the prices are weird not sure how those exist but the years can go back as far as needed no?

**Comment by leenlab2** [comment]
> Why do you only want to include if the year is 2019, 2020? I agree the prices are weird not sure how those exist but the years can go back as far as needed no?

That's because this dataset contains used cars, for our purposes we don't really need that many. The prices are wayyy too low for the other stuff.

**Pull request merged**
