### PR TITLE
Removed hard coded values and made global variables

### PR DESCRIPTION
**Pull request by dhruvaa02**
## Context

Currently had hard coded values for thing such as the number of cars being returned.

Related to issue #42 

## Your Changes

**Description**:

Refactored the hard coded values.

**Type of change** (select all that apply):

- [x] Refactoring (changing code structure only)

## Testing

Ran the automated tests and everything works as before.

## Checklist

- [x] Code is up to date with main branch (no merge conflicts)
- [x] Code has been properly tested
- [x] Code has been properly documented
- [ ] One or two people have reviewed this pull request

### CODE REVIEW

**Review by Infinityworld13 — COMMENTED** [review]
We might want to change the new attributes to be private, since we only want their respective class to utilize them. Apart from that it works well

**Comment by dhruvaa02** [comment]
> We might want to change the new attributes to be private, since we only want their respective class to utilize them. Apart from that it works well

Done

**Review by nguya03584 — APPROVED** [review]
Everything seems good!

**Comment by Alamgir-K** [comment]
I'm not a reviewer for this but I really think we should have a constants file/package because these values get used in more than just this part of the code

**Pull request closed without merging**
